# Generated by Django 4.2.4 on 2023-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropout',
            name='custom_reason',
            field=models.TextField(blank=True, help_text="Please provide your custom reason here if you selected 'Other Reason' above.", null=True, verbose_name='Custom Reason'),
        ),
        migrations.AlterField(
            model_name='dropout',
            name='reason',
            field=models.CharField(choices=[('lack_of_interest', 'Lack of Interest'), ('financial_issues', 'Financial Issues'), ('personal_reasons', 'Personal Reasons'), ('academic_difficulties', 'Academic Difficulties'), ('other_reason', 'Other Reason')], default='lack_of_interest', max_length=50),
        ),
    ]
