# Generated by Django 4.2.4 on 2023-08-31 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_dropout_custom_reason_alter_dropout_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='area',
            new_name='city',
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
